/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardDemoRouteImport } from './routes/_authenticated/dashboard-demo'
import { Route as AuthenticatedAiDocumentsRouteImport } from './routes/_authenticated/ai-documents'
import { Route as AuthenticatedAiContentRouteImport } from './routes/_authenticated/ai-content'
import { Route as AuthenticatedAiAnalyticsRouteImport } from './routes/_authenticated/ai-analytics'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authCheckEmailRouteImport } from './routes/(auth)/check-email'
import { Route as authAcceptInvitationRouteImport } from './routes/(auth)/accept-invitation'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing/index'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDemoUsersRouteImport } from './routes/_authenticated/demo/users'
import { Route as AuthenticatedDemoTasksRouteImport } from './routes/_authenticated/demo/tasks'
import { Route as AuthenticatedDemoHelpCenterRouteImport } from './routes/_authenticated/demo/help-center'
import { Route as AuthenticatedDemoDashboardDemoRouteImport } from './routes/_authenticated/demo/dashboard-demo'
import { Route as AuthenticatedDemoChatsRouteImport } from './routes/_authenticated/demo/chats'
import { Route as AuthenticatedDemoAppsRouteImport } from './routes/_authenticated/demo/apps'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminActivityLogsRouteImport } from './routes/_authenticated/admin/activity-logs'
import { Route as AuthenticatedDemoSettingsRouteRouteImport } from './routes/_authenticated/demo/settings/route'
import { Route as AuthenticatedOrganizationsOrganizationIdIndexRouteImport } from './routes/_authenticated/organizations/$organizationId/index'
import { Route as AuthenticatedDemoSettingsIndexRouteImport } from './routes/_authenticated/demo/settings/index'
import { Route as AuthenticatedDemoSettingsNotificationsRouteImport } from './routes/_authenticated/demo/settings/notifications'
import { Route as AuthenticatedDemoSettingsDisplayRouteImport } from './routes/_authenticated/demo/settings/display'
import { Route as AuthenticatedDemoSettingsAppearanceRouteImport } from './routes/_authenticated/demo/settings/appearance'
import { Route as AuthenticatedDemoSettingsAccountRouteImport } from './routes/_authenticated/demo/settings/account'
import { Route as authOauthMicrosoftCallbackRouteImport } from './routes/(auth)/oauth/microsoft/callback'
import { Route as authOauthGoogleCallbackRouteImport } from './routes/(auth)/oauth/google/callback'
import { Route as authOauthGithubCallbackRouteImport } from './routes/(auth)/oauth/github/callback'
import { Route as authOauthAppleCallbackRouteImport } from './routes/(auth)/oauth/apple/callback'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardDemoRoute =
  AuthenticatedDashboardDemoRouteImport.update({
    id: '/dashboard-demo',
    path: '/dashboard-demo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiDocumentsRoute =
  AuthenticatedAiDocumentsRouteImport.update({
    id: '/ai-documents',
    path: '/ai-documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiContentRoute = AuthenticatedAiContentRouteImport.update({
  id: '/ai-content',
  path: '/ai-content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAnalyticsRoute =
  AuthenticatedAiAnalyticsRouteImport.update({
    id: '/ai-analytics',
    path: '/ai-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/(auth)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authCheckEmailRoute = authCheckEmailRouteImport.update({
  id: '/(auth)/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authAcceptInvitationRoute = authAcceptInvitationRouteImport.update({
  id: '/(auth)/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoUsersRoute = AuthenticatedDemoUsersRouteImport.update({
  id: '/demo/users',
  path: '/demo/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoTasksRoute = AuthenticatedDemoTasksRouteImport.update({
  id: '/demo/tasks',
  path: '/demo/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoHelpCenterRoute =
  AuthenticatedDemoHelpCenterRouteImport.update({
    id: '/demo/help-center',
    path: '/demo/help-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoDashboardDemoRoute =
  AuthenticatedDemoDashboardDemoRouteImport.update({
    id: '/demo/dashboard-demo',
    path: '/demo/dashboard-demo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoChatsRoute = AuthenticatedDemoChatsRouteImport.update({
  id: '/demo/chats',
  path: '/demo/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoAppsRoute = AuthenticatedDemoAppsRouteImport.update({
  id: '/demo/apps',
  path: '/demo/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivityLogsRoute =
  AuthenticatedAdminActivityLogsRouteImport.update({
    id: '/admin/activity-logs',
    path: '/admin/activity-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoSettingsRouteRoute =
  AuthenticatedDemoSettingsRouteRouteImport.update({
    id: '/demo/settings',
    path: '/demo/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrganizationIdIndexRoute =
  AuthenticatedOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoSettingsIndexRoute =
  AuthenticatedDemoSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsNotificationsRoute =
  AuthenticatedDemoSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsDisplayRoute =
  AuthenticatedDemoSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsAppearanceRoute =
  AuthenticatedDemoSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsAccountRoute =
  AuthenticatedDemoSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const authOauthMicrosoftCallbackRoute =
  authOauthMicrosoftCallbackRouteImport.update({
    id: '/(auth)/oauth/microsoft/callback',
    path: '/oauth/microsoft/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const authOauthGoogleCallbackRoute = authOauthGoogleCallbackRouteImport.update({
  id: '/(auth)/oauth/google/callback',
  path: '/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const authOauthGithubCallbackRoute = authOauthGithubCallbackRouteImport.update({
  id: '/(auth)/oauth/github/callback',
  path: '/oauth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const authOauthAppleCallbackRoute = authOauthAppleCallbackRouteImport.update({
  id: '/(auth)/oauth/apple/callback',
  path: '/oauth/apple/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/check-email': typeof authCheckEmailRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ai-analytics': typeof AuthenticatedAiAnalyticsRoute
  '/ai-content': typeof AuthenticatedAiContentRoute
  '/ai-documents': typeof AuthenticatedAiDocumentsRoute
  '/dashboard-demo': typeof AuthenticatedDashboardDemoRoute
  '/': typeof AuthenticatedIndexRoute
  '/demo/settings': typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  '/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/demo/apps': typeof AuthenticatedDemoAppsRoute
  '/demo/chats': typeof AuthenticatedDemoChatsRoute
  '/demo/dashboard-demo': typeof AuthenticatedDemoDashboardDemoRoute
  '/demo/help-center': typeof AuthenticatedDemoHelpCenterRoute
  '/demo/tasks': typeof AuthenticatedDemoTasksRoute
  '/demo/users': typeof AuthenticatedDemoUsersRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/oauth/apple/callback': typeof authOauthAppleCallbackRoute
  '/oauth/github/callback': typeof authOauthGithubCallbackRoute
  '/oauth/google/callback': typeof authOauthGoogleCallbackRoute
  '/oauth/microsoft/callback': typeof authOauthMicrosoftCallbackRoute
  '/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/demo/settings/': typeof AuthenticatedDemoSettingsIndexRoute
  '/organizations/$organizationId': typeof AuthenticatedOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof authAcceptInvitationRoute
  '/check-email': typeof authCheckEmailRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ai-analytics': typeof AuthenticatedAiAnalyticsRoute
  '/ai-content': typeof AuthenticatedAiContentRoute
  '/ai-documents': typeof AuthenticatedAiDocumentsRoute
  '/dashboard-demo': typeof AuthenticatedDashboardDemoRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/demo/apps': typeof AuthenticatedDemoAppsRoute
  '/demo/chats': typeof AuthenticatedDemoChatsRoute
  '/demo/dashboard-demo': typeof AuthenticatedDemoDashboardDemoRoute
  '/demo/help-center': typeof AuthenticatedDemoHelpCenterRoute
  '/demo/tasks': typeof AuthenticatedDemoTasksRoute
  '/demo/users': typeof AuthenticatedDemoUsersRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/oauth/apple/callback': typeof authOauthAppleCallbackRoute
  '/oauth/github/callback': typeof authOauthGithubCallbackRoute
  '/oauth/google/callback': typeof authOauthGoogleCallbackRoute
  '/oauth/microsoft/callback': typeof authOauthMicrosoftCallbackRoute
  '/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/demo/settings': typeof AuthenticatedDemoSettingsIndexRoute
  '/organizations/$organizationId': typeof AuthenticatedOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/accept-invitation': typeof authAcceptInvitationRoute
  '/(auth)/check-email': typeof authCheckEmailRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/ai-analytics': typeof AuthenticatedAiAnalyticsRoute
  '/_authenticated/ai-content': typeof AuthenticatedAiContentRoute
  '/_authenticated/ai-documents': typeof AuthenticatedAiDocumentsRoute
  '/_authenticated/dashboard-demo': typeof AuthenticatedDashboardDemoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/demo/settings': typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  '/_authenticated/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/demo/apps': typeof AuthenticatedDemoAppsRoute
  '/_authenticated/demo/chats': typeof AuthenticatedDemoChatsRoute
  '/_authenticated/demo/dashboard-demo': typeof AuthenticatedDemoDashboardDemoRoute
  '/_authenticated/demo/help-center': typeof AuthenticatedDemoHelpCenterRoute
  '/_authenticated/demo/tasks': typeof AuthenticatedDemoTasksRoute
  '/_authenticated/demo/users': typeof AuthenticatedDemoUsersRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/(auth)/oauth/apple/callback': typeof authOauthAppleCallbackRoute
  '/(auth)/oauth/github/callback': typeof authOauthGithubCallbackRoute
  '/(auth)/oauth/google/callback': typeof authOauthGoogleCallbackRoute
  '/(auth)/oauth/microsoft/callback': typeof authOauthMicrosoftCallbackRoute
  '/_authenticated/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/_authenticated/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/_authenticated/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/_authenticated/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/_authenticated/demo/settings/': typeof AuthenticatedDemoSettingsIndexRoute
  '/_authenticated/organizations/$organizationId/': typeof AuthenticatedOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/accept-invitation'
    | '/check-email'
    | '/forgot-password'
    | '/onboarding'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ai-analytics'
    | '/ai-content'
    | '/ai-documents'
    | '/dashboard-demo'
    | '/'
    | '/demo/settings'
    | '/admin/activity-logs'
    | '/admin/reports'
    | '/admin/users'
    | '/demo/apps'
    | '/demo/chats'
    | '/demo/dashboard-demo'
    | '/demo/help-center'
    | '/demo/tasks'
    | '/demo/users'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/organizations'
    | '/pricing'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/oauth/apple/callback'
    | '/oauth/github/callback'
    | '/oauth/google/callback'
    | '/oauth/microsoft/callback'
    | '/demo/settings/account'
    | '/demo/settings/appearance'
    | '/demo/settings/display'
    | '/demo/settings/notifications'
    | '/demo/settings/'
    | '/organizations/$organizationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/check-email'
    | '/forgot-password'
    | '/onboarding'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ai-analytics'
    | '/ai-content'
    | '/ai-documents'
    | '/dashboard-demo'
    | '/'
    | '/admin/activity-logs'
    | '/admin/reports'
    | '/admin/users'
    | '/demo/apps'
    | '/demo/chats'
    | '/demo/dashboard-demo'
    | '/demo/help-center'
    | '/demo/tasks'
    | '/demo/users'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/organizations'
    | '/pricing'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/oauth/apple/callback'
    | '/oauth/github/callback'
    | '/oauth/google/callback'
    | '/oauth/microsoft/callback'
    | '/demo/settings/account'
    | '/demo/settings/appearance'
    | '/demo/settings/display'
    | '/demo/settings/notifications'
    | '/demo/settings'
    | '/organizations/$organizationId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/accept-invitation'
    | '/(auth)/check-email'
    | '/(auth)/forgot-password'
    | '/(auth)/onboarding'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/ai-analytics'
    | '/_authenticated/ai-content'
    | '/_authenticated/ai-documents'
    | '/_authenticated/dashboard-demo'
    | '/_authenticated/'
    | '/_authenticated/demo/settings'
    | '/_authenticated/admin/activity-logs'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/demo/apps'
    | '/_authenticated/demo/chats'
    | '/_authenticated/demo/dashboard-demo'
    | '/_authenticated/demo/help-center'
    | '/_authenticated/demo/tasks'
    | '/_authenticated/demo/users'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/organizations/'
    | '/_authenticated/pricing/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/(auth)/oauth/apple/callback'
    | '/(auth)/oauth/github/callback'
    | '/(auth)/oauth/google/callback'
    | '/(auth)/oauth/microsoft/callback'
    | '/_authenticated/demo/settings/account'
    | '/_authenticated/demo/settings/appearance'
    | '/_authenticated/demo/settings/display'
    | '/_authenticated/demo/settings/notifications'
    | '/_authenticated/demo/settings/'
    | '/_authenticated/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authAcceptInvitationRoute: typeof authAcceptInvitationRoute
  authCheckEmailRoute: typeof authCheckEmailRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  authOauthAppleCallbackRoute: typeof authOauthAppleCallbackRoute
  authOauthGithubCallbackRoute: typeof authOauthGithubCallbackRoute
  authOauthGoogleCallbackRoute: typeof authOauthGoogleCallbackRoute
  authOauthMicrosoftCallbackRoute: typeof authOauthMicrosoftCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-demo': {
      id: '/_authenticated/dashboard-demo'
      path: '/dashboard-demo'
      fullPath: '/dashboard-demo'
      preLoaderRoute: typeof AuthenticatedDashboardDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-documents': {
      id: '/_authenticated/ai-documents'
      path: '/ai-documents'
      fullPath: '/ai-documents'
      preLoaderRoute: typeof AuthenticatedAiDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-content': {
      id: '/_authenticated/ai-content'
      path: '/ai-content'
      fullPath: '/ai-content'
      preLoaderRoute: typeof AuthenticatedAiContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-analytics': {
      id: '/_authenticated/ai-analytics'
      path: '/ai-analytics'
      fullPath: '/ai-analytics'
      preLoaderRoute: typeof AuthenticatedAiAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/check-email': {
      id: '/(auth)/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof authCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/accept-invitation': {
      id: '/(auth)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof authAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/users': {
      id: '/_authenticated/demo/users'
      path: '/demo/users'
      fullPath: '/demo/users'
      preLoaderRoute: typeof AuthenticatedDemoUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/tasks': {
      id: '/_authenticated/demo/tasks'
      path: '/demo/tasks'
      fullPath: '/demo/tasks'
      preLoaderRoute: typeof AuthenticatedDemoTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/help-center': {
      id: '/_authenticated/demo/help-center'
      path: '/demo/help-center'
      fullPath: '/demo/help-center'
      preLoaderRoute: typeof AuthenticatedDemoHelpCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/dashboard-demo': {
      id: '/_authenticated/demo/dashboard-demo'
      path: '/demo/dashboard-demo'
      fullPath: '/demo/dashboard-demo'
      preLoaderRoute: typeof AuthenticatedDemoDashboardDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/chats': {
      id: '/_authenticated/demo/chats'
      path: '/demo/chats'
      fullPath: '/demo/chats'
      preLoaderRoute: typeof AuthenticatedDemoChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/apps': {
      id: '/_authenticated/demo/apps'
      path: '/demo/apps'
      fullPath: '/demo/apps'
      preLoaderRoute: typeof AuthenticatedDemoAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activity-logs': {
      id: '/_authenticated/admin/activity-logs'
      path: '/admin/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/settings': {
      id: '/_authenticated/demo/settings'
      path: '/demo/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof AuthenticatedDemoSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/$organizationId/': {
      id: '/_authenticated/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/settings/': {
      id: '/_authenticated/demo/settings/'
      path: '/'
      fullPath: '/demo/settings/'
      preLoaderRoute: typeof AuthenticatedDemoSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/notifications': {
      id: '/_authenticated/demo/settings/notifications'
      path: '/notifications'
      fullPath: '/demo/settings/notifications'
      preLoaderRoute: typeof AuthenticatedDemoSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/display': {
      id: '/_authenticated/demo/settings/display'
      path: '/display'
      fullPath: '/demo/settings/display'
      preLoaderRoute: typeof AuthenticatedDemoSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/appearance': {
      id: '/_authenticated/demo/settings/appearance'
      path: '/appearance'
      fullPath: '/demo/settings/appearance'
      preLoaderRoute: typeof AuthenticatedDemoSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/account': {
      id: '/_authenticated/demo/settings/account'
      path: '/account'
      fullPath: '/demo/settings/account'
      preLoaderRoute: typeof AuthenticatedDemoSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/(auth)/oauth/microsoft/callback': {
      id: '/(auth)/oauth/microsoft/callback'
      path: '/oauth/microsoft/callback'
      fullPath: '/oauth/microsoft/callback'
      preLoaderRoute: typeof authOauthMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/oauth/google/callback': {
      id: '/(auth)/oauth/google/callback'
      path: '/oauth/google/callback'
      fullPath: '/oauth/google/callback'
      preLoaderRoute: typeof authOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/oauth/github/callback': {
      id: '/(auth)/oauth/github/callback'
      path: '/oauth/github/callback'
      fullPath: '/oauth/github/callback'
      preLoaderRoute: typeof authOauthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/oauth/apple/callback': {
      id: '/(auth)/oauth/apple/callback'
      path: '/oauth/apple/callback'
      fullPath: '/oauth/apple/callback'
      preLoaderRoute: typeof authOauthAppleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedDemoSettingsRouteRouteChildren {
  AuthenticatedDemoSettingsAccountRoute: typeof AuthenticatedDemoSettingsAccountRoute
  AuthenticatedDemoSettingsAppearanceRoute: typeof AuthenticatedDemoSettingsAppearanceRoute
  AuthenticatedDemoSettingsDisplayRoute: typeof AuthenticatedDemoSettingsDisplayRoute
  AuthenticatedDemoSettingsNotificationsRoute: typeof AuthenticatedDemoSettingsNotificationsRoute
  AuthenticatedDemoSettingsIndexRoute: typeof AuthenticatedDemoSettingsIndexRoute
}

const AuthenticatedDemoSettingsRouteRouteChildren: AuthenticatedDemoSettingsRouteRouteChildren =
  {
    AuthenticatedDemoSettingsAccountRoute:
      AuthenticatedDemoSettingsAccountRoute,
    AuthenticatedDemoSettingsAppearanceRoute:
      AuthenticatedDemoSettingsAppearanceRoute,
    AuthenticatedDemoSettingsDisplayRoute:
      AuthenticatedDemoSettingsDisplayRoute,
    AuthenticatedDemoSettingsNotificationsRoute:
      AuthenticatedDemoSettingsNotificationsRoute,
    AuthenticatedDemoSettingsIndexRoute: AuthenticatedDemoSettingsIndexRoute,
  }

const AuthenticatedDemoSettingsRouteRouteWithChildren =
  AuthenticatedDemoSettingsRouteRoute._addFileChildren(
    AuthenticatedDemoSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAiAnalyticsRoute: typeof AuthenticatedAiAnalyticsRoute
  AuthenticatedAiContentRoute: typeof AuthenticatedAiContentRoute
  AuthenticatedAiDocumentsRoute: typeof AuthenticatedAiDocumentsRoute
  AuthenticatedDashboardDemoRoute: typeof AuthenticatedDashboardDemoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemoSettingsRouteRoute: typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  AuthenticatedAdminActivityLogsRoute: typeof AuthenticatedAdminActivityLogsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedDemoAppsRoute: typeof AuthenticatedDemoAppsRoute
  AuthenticatedDemoChatsRoute: typeof AuthenticatedDemoChatsRoute
  AuthenticatedDemoDashboardDemoRoute: typeof AuthenticatedDemoDashboardDemoRoute
  AuthenticatedDemoHelpCenterRoute: typeof AuthenticatedDemoHelpCenterRoute
  AuthenticatedDemoTasksRoute: typeof AuthenticatedDemoTasksRoute
  AuthenticatedDemoUsersRoute: typeof AuthenticatedDemoUsersRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedOrganizationsOrganizationIdIndexRoute: typeof AuthenticatedOrganizationsOrganizationIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAiAnalyticsRoute: AuthenticatedAiAnalyticsRoute,
  AuthenticatedAiContentRoute: AuthenticatedAiContentRoute,
  AuthenticatedAiDocumentsRoute: AuthenticatedAiDocumentsRoute,
  AuthenticatedDashboardDemoRoute: AuthenticatedDashboardDemoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemoSettingsRouteRoute:
    AuthenticatedDemoSettingsRouteRouteWithChildren,
  AuthenticatedAdminActivityLogsRoute: AuthenticatedAdminActivityLogsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedDemoAppsRoute: AuthenticatedDemoAppsRoute,
  AuthenticatedDemoChatsRoute: AuthenticatedDemoChatsRoute,
  AuthenticatedDemoDashboardDemoRoute: AuthenticatedDemoDashboardDemoRoute,
  AuthenticatedDemoHelpCenterRoute: AuthenticatedDemoHelpCenterRoute,
  AuthenticatedDemoTasksRoute: AuthenticatedDemoTasksRoute,
  AuthenticatedDemoUsersRoute: AuthenticatedDemoUsersRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedOrganizationsOrganizationIdIndexRoute:
    AuthenticatedOrganizationsOrganizationIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authAcceptInvitationRoute: authAcceptInvitationRoute,
  authCheckEmailRoute: authCheckEmailRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOnboardingRoute: authOnboardingRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  authOauthAppleCallbackRoute: authOauthAppleCallbackRoute,
  authOauthGithubCallbackRoute: authOauthGithubCallbackRoute,
  authOauthGoogleCallbackRoute: authOauthGoogleCallbackRoute,
  authOauthMicrosoftCallbackRoute: authOauthMicrosoftCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
