// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client'
import { client } from './client.gen'
import type {
  AdminActivitylogsListData,
  AdminActivitylogsListErrors,
  AdminActivitylogsListResponses,
  AdminAnalyticsOverviewListData,
  AdminAnalyticsOverviewListResponses,
  AdminAnalyticsRevenuechartListData,
  AdminAnalyticsRevenuechartListErrors,
  AdminAnalyticsRevenuechartListResponses,
  AdminAnalyticsUsersgrowthListData,
  AdminAnalyticsUsersgrowthListErrors,
  AdminAnalyticsUsersgrowthListResponses,
  AdminStatsListData,
  AdminStatsListResponses,
  AdminUsersDeleteByIdData,
  AdminUsersDeleteByIdErrors,
  AdminUsersDeleteByIdResponses,
  AdminUsersGetByIdData,
  AdminUsersGetByIdErrors,
  AdminUsersGetByIdResponses,
  AdminUsersInviteCreateData,
  AdminUsersInviteCreateErrors,
  AdminUsersInviteCreateResponses,
  AdminUsersListData,
  AdminUsersListErrors,
  AdminUsersListResponses,
  AdminUsersUpdateByIdData,
  AdminUsersUpdateByIdErrors,
  AdminUsersUpdateByIdResponses,
  AiAnalyticsInsightsListData,
  AiAnalyticsInsightsListResponses,
  AiAnalyticsQueriesGetByIdData,
  AiAnalyticsQueriesGetByIdErrors,
  AiAnalyticsQueriesGetByIdResponses,
  AiAnalyticsQueriesListData,
  AiAnalyticsQueriesListErrors,
  AiAnalyticsQueriesListResponses,
  AiAnalyticsQueryCreateData,
  AiAnalyticsQueryCreateErrors,
  AiAnalyticsQueryCreateResponses,
  AiAnalyticsStatsListData,
  AiAnalyticsStatsListResponses,
  AiBillingBillingperiodListData,
  AiBillingBillingperiodListErrors,
  AiBillingBillingperiodListResponses,
  AiBillingChecklimitsListData,
  AiBillingChecklimitsListErrors,
  AiBillingChecklimitsListResponses,
  AiBillingMonthlyreportListData,
  AiBillingMonthlyreportListErrors,
  AiBillingMonthlyreportListResponses,
  AiBillingStatsListData,
  AiBillingStatsListResponses,
  AiBillingUsagesummaryListData,
  AiBillingUsagesummaryListErrors,
  AiBillingUsagesummaryListResponses,
  AiContentGenerateCreateData,
  AiContentGenerateCreateErrors,
  AiContentGenerateCreateResponses,
  AiContentGenerationsGetByIdData,
  AiContentGenerationsGetByIdErrors,
  AiContentGenerationsGetByIdResponses,
  AiContentGenerationsListData,
  AiContentGenerationsListErrors,
  AiContentGenerationsListResponses,
  AiContentListData,
  AiContentListResponses,
  AiContentStatsListData,
  AiContentStatsListResponses,
  AiContentTemplatesCreateData,
  AiContentTemplatesCreateErrors,
  AiContentTemplatesCreateResponses,
  AiContentTemplatesDeleteByIdData,
  AiContentTemplatesDeleteByIdErrors,
  AiContentTemplatesDeleteByIdResponses,
  AiContentTemplatesGetByIdData,
  AiContentTemplatesGetByIdErrors,
  AiContentTemplatesGetByIdResponses,
  AiContentTemplatesListData,
  AiContentTemplatesListErrors,
  AiContentTemplatesListResponses,
  AiContentTemplatesUpdateByIdData,
  AiContentTemplatesUpdateByIdErrors,
  AiContentTemplatesUpdateByIdResponses,
  AiDashboardInsightsListData,
  AiDashboardInsightsListResponses,
  AiDashboardMetricsListData,
  AiDashboardMetricsListResponses,
  AiDashboardOverviewListData,
  AiDashboardOverviewListResponses,
  AiDashboardTrendsListData,
  AiDashboardTrendsListErrors,
  AiDashboardTrendsListResponses,
  AiDocumentsChatCreateByIdData,
  AiDocumentsChatCreateByIdErrors,
  AiDocumentsChatCreateByIdResponses,
  AiDocumentsChatsGetByIdData,
  AiDocumentsChatsGetByIdErrors,
  AiDocumentsChatsGetByIdResponses,
  AiDocumentsDeleteByIdData,
  AiDocumentsDeleteByIdErrors,
  AiDocumentsDeleteByIdResponses,
  AiDocumentsGetByIdData,
  AiDocumentsGetByIdErrors,
  AiDocumentsGetByIdResponses,
  AiDocumentsListData,
  AiDocumentsListErrors,
  AiDocumentsListResponses,
  AiDocumentsStatusGetByIdData,
  AiDocumentsStatusGetByIdErrors,
  AiDocumentsStatusGetByIdResponses,
  AiDocumentsUploadCreateData,
  AiDocumentsUploadCreateErrors,
  AiDocumentsUploadCreateResponses,
  AiUsageDashboardListData,
  AiUsageDashboardListResponses,
  AiUsageLimitsListData,
  AiUsageLimitsListResponses,
  AiUsageRecentactivityListData,
  AiUsageRecentactivityListResponses,
  AuthForgotpasswordData,
  AuthForgotpasswordErrors,
  AuthForgotpasswordResponses,
  AuthGetsessionListData,
  AuthGetsessionListResponses,
  AuthJwtLoginCreateData,
  AuthJwtLoginCreateErrors,
  AuthJwtLoginCreateResponses,
  AuthJwtLogoutCreateData,
  AuthJwtLogoutCreateErrors,
  AuthJwtLogoutCreateResponses,
  AuthOauthAuthorizeGetByIdData,
  AuthOauthAuthorizeGetByIdErrors,
  AuthOauthAuthorizeGetByIdResponses,
  AuthOauthCallbackData,
  AuthOauthCallbackErrors,
  AuthOauthCallbackResponses,
  AuthOauthLinkcallbackData,
  AuthOauthLinkcallbackErrors,
  AuthOauthLinkcallbackResponses,
  AuthOauthLinkCreateByIdData,
  AuthOauthLinkCreateByIdErrors,
  AuthOauthLinkCreateByIdResponses,
  AuthOauthProvidersListData,
  AuthOauthProvidersListResponses,
  AuthOauthUnlinkCreateByIdData,
  AuthOauthUnlinkCreateByIdErrors,
  AuthOauthUnlinkCreateByIdResponses,
  AuthOnboardingCompleteCreateData,
  AuthOnboardingCompleteCreateErrors,
  AuthOnboardingCompleteCreateResponses,
  AuthOnboardingOrganizationCreateData,
  AuthOnboardingOrganizationCreateResponses,
  AuthOnboardingProfileUpdateData,
  AuthOnboardingProfileUpdateErrors,
  AuthOnboardingProfileUpdateResponses,
  AuthOnboardingSaveallCreateData,
  AuthOnboardingSaveallCreateResponses,
  AuthOnboardingStatusListData,
  AuthOnboardingStatusListResponses,
  AuthOnboardingStepUpdateData,
  AuthOnboardingStepUpdateErrors,
  AuthOnboardingStepUpdateResponses,
  AuthOrganizationAcceptinvitationCreateData,
  AuthOrganizationAcceptinvitationCreateResponses,
  AuthOrganizationCancelinvitationCreateData,
  AuthOrganizationCancelinvitationCreateResponses,
  AuthOrganizationCreateCreateData,
  AuthOrganizationCreateCreateResponses,
  AuthOrganizationCreateData,
  AuthOrganizationCreateResponses,
  AuthOrganizationDeleteByIdData,
  AuthOrganizationDeleteByIdErrors,
  AuthOrganizationDeleteByIdResponses,
  AuthOrganizationGetByIdData,
  AuthOrganizationGetByIdErrors,
  AuthOrganizationGetByIdResponses,
  AuthOrganizationInvitememberCreateData,
  AuthOrganizationInvitememberCreateResponses,
  AuthOrganizationListData,
  AuthOrganizationListinvitationsListData,
  AuthOrganizationListinvitationsListResponses,
  AuthOrganizationListListData,
  AuthOrganizationListListResponses,
  AuthOrganizationListmembersListData,
  AuthOrganizationListmembersListResponses,
  AuthOrganizationListResponses,
  AuthOrganizationListuserinvitationsListData,
  AuthOrganizationListuserinvitationsListResponses,
  AuthOrganizationRejectinvitationCreateData,
  AuthOrganizationRejectinvitationCreateResponses,
  AuthOrganizationRemovememberCreateData,
  AuthOrganizationRemovememberCreateResponses,
  AuthOrganizationSetactiveCreateData,
  AuthOrganizationSetactiveCreateResponses,
  AuthOrganizationUpdateByIdData,
  AuthOrganizationUpdateByIdErrors,
  AuthOrganizationUpdateByIdResponses,
  AuthOrganizationUpdatememberroleCreateData,
  AuthOrganizationUpdatememberroleCreateResponses,
  AuthOtpSendCreateData,
  AuthOtpSendCreateErrors,
  AuthOtpSendCreateResponses,
  AuthOtpVerifyData,
  AuthOtpVerifyErrors,
  AuthOtpVerifyResponses,
  AuthRegisterCreateData,
  AuthRegisterCreateErrors,
  AuthRegisterCreateResponses,
  AuthRequestverifytokenData,
  AuthRequestverifytokenErrors,
  AuthRequestverifytokenResponses,
  AuthResendverificationData,
  AuthResendverificationErrors,
  AuthResendverificationResponses,
  AuthResetpasswordData,
  AuthResetpasswordErrors,
  AuthResetpasswordResponses,
  AuthSessionListData,
  AuthSessionListResponses,
  AuthSigninEmailData,
  AuthSigninEmailErrors,
  AuthSigninEmailResponses,
  AuthSignoutData,
  AuthSignoutResponses,
  AuthSignupEmailData,
  AuthSignupEmailErrors,
  AuthSignupEmailResponses,
  AuthVerifyData,
  AuthVerifyemailData,
  AuthVerifyemailErrors,
  AuthVerifyemailResponses,
  AuthVerifyErrors,
  AuthVerifyResponses,
  HealthListData,
  HealthListResponses,
  I18nDatetimeListData,
  I18nDatetimeListResponses,
  I18nLanguagesListData,
  I18nLanguagesListResponses,
  I18nPluralizationListData,
  I18nPluralizationListErrors,
  I18nPluralizationListResponses,
  I18nTestListData,
  I18nTestListErrors,
  I18nTestListResponses,
  InvitationsInvitationsAcceptCreateByIdData,
  InvitationsInvitationsAcceptCreateByIdErrors,
  InvitationsInvitationsAcceptCreateByIdResponses,
  InvitationsInvitationsDeclineCreateByIdData,
  InvitationsInvitationsDeclineCreateByIdErrors,
  InvitationsInvitationsDeclineCreateByIdResponses,
  InvitationsOrganizationsInvitationsCreateByIdData,
  InvitationsOrganizationsInvitationsCreateByIdErrors,
  InvitationsOrganizationsInvitationsCreateByIdResponses,
  InvitationsOrganizationsInvitationsDeleteByIdData,
  InvitationsOrganizationsInvitationsDeleteByIdErrors,
  InvitationsOrganizationsInvitationsDeleteByIdResponses,
  InvitationsOrganizationsInvitationsGetByIdData,
  InvitationsOrganizationsInvitationsGetByIdErrors,
  InvitationsOrganizationsInvitationsGetByIdResponses,
  InvitationsVerifyemailData,
  InvitationsVerifyemailErrors,
  InvitationsVerifyemailResendData,
  InvitationsVerifyemailResendResponses,
  InvitationsVerifyemailResponses,
  MeListData,
  MeListResponses,
  MetricsEndpointsListData,
  MetricsEndpointsListResponses,
  MetricsListData,
  MetricsListResponses,
  MetricsRecentListData,
  MetricsRecentListErrors,
  MetricsRecentListResponses,
  MeUpdateData,
  MeUpdateErrors,
  MeUpdateResponses,
  OrganizationsCreateData,
  OrganizationsCreateErrors,
  OrganizationsCreateResponses,
  OrganizationsExportCsvListData,
  OrganizationsExportCsvListResponses,
  OrganizationsExportJsonListData,
  OrganizationsExportJsonListResponses,
  OrganizationsInviteCreateByIdData,
  OrganizationsInviteCreateByIdErrors,
  OrganizationsInviteCreateByIdResponses,
  OrganizationsListData,
  OrganizationsListErrors,
  OrganizationsListResponses,
  OrganizationsLogoDeleteByIdData,
  OrganizationsLogoDeleteByIdErrors,
  OrganizationsLogoDeleteByIdResponses,
  OrganizationsUploadlogoCreateByIdData,
  OrganizationsUploadlogoCreateByIdErrors,
  OrganizationsUploadlogoCreateByIdResponses,
  PaymentsPlansListData,
  PaymentsPlansListErrors,
  PaymentsPlansListResponses,
  PaymentsStripewebhookCreateData,
  PaymentsStripewebhookCreateResponses,
  PaymentsSubscribeCreateByIdData,
  PaymentsSubscribeCreateByIdErrors,
  PaymentsSubscribeCreateByIdResponses,
  ProjectsCreateData,
  ProjectsCreateErrors,
  ProjectsCreateResponses,
  ProjectsDeleteByIdData,
  ProjectsDeleteByIdErrors,
  ProjectsDeleteByIdResponses,
  ProjectsExportCsvListData,
  ProjectsExportCsvListResponses,
  ProjectsExportJsonListData,
  ProjectsExportJsonListResponses,
  ProjectsGetByIdData,
  ProjectsGetByIdErrors,
  ProjectsGetByIdResponses,
  ProjectsListData,
  ProjectsListErrors,
  ProjectsListResponses,
  ProjectsUpdateByIdData,
  ProjectsUpdateByIdErrors,
  ProjectsUpdateByIdResponses,
  SubscriptionsOrganizationsBillinghistoryGetByIdData,
  SubscriptionsOrganizationsBillinghistoryGetByIdErrors,
  SubscriptionsOrganizationsBillinghistoryGetByIdResponses,
  SubscriptionsOrganizationsCancelCreateByIdData,
  SubscriptionsOrganizationsCancelCreateByIdErrors,
  SubscriptionsOrganizationsCancelCreateByIdResponses,
  SubscriptionsOrganizationsCheckoutCreateByIdData,
  SubscriptionsOrganizationsCheckoutCreateByIdErrors,
  SubscriptionsOrganizationsCheckoutCreateByIdResponses,
  SubscriptionsOrganizationsPortalCreateByIdData,
  SubscriptionsOrganizationsPortalCreateByIdErrors,
  SubscriptionsOrganizationsPortalCreateByIdResponses,
  SubscriptionsOrganizationsSubscriptionGetByIdData,
  SubscriptionsOrganizationsSubscriptionGetByIdErrors,
  SubscriptionsOrganizationsSubscriptionGetByIdResponses,
  SubscriptionsOrganizationsUsageGetByIdData,
  SubscriptionsOrganizationsUsageGetByIdErrors,
  SubscriptionsOrganizationsUsageGetByIdResponses,
  SubscriptionsPlansListData,
  SubscriptionsPlansListErrors,
  SubscriptionsPlansListResponses,
  UploadsCreateData,
  UploadsCreateErrors,
  UploadsCreateResponses,
  UploadsDeleteByIdData,
  UploadsDeleteByIdErrors,
  UploadsDeleteByIdResponses,
  UploadsUrlGetByIdData,
  UploadsUrlGetByIdErrors,
  UploadsUrlGetByIdResponses,
  UsersGetByIdData,
  UsersGetByIdErrors,
  UsersGetByIdResponses,
  UsersListData,
  UsersListErrors,
  UsersListResponses,
  UsersMeImageDeleteData,
  UsersMeImageDeleteResponses,
  UsersMeListData,
  UsersMeListResponses,
  UsersMeUpdateData,
  UsersMeUpdateErrors,
  UsersMeUpdateResponses,
  UsersMeUploadimageCreateData,
  UsersMeUploadimageCreateErrors,
  UsersMeUploadimageCreateResponses,
  WebhooksStripeCreateData,
  WebhooksStripeCreateResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Health Check
 *
 * Health check endpoint for monitoring and Docker healthcheck
 */
export const healthList = <ThrowOnError extends boolean = false>(
  options?: Options<HealthListData, ThrowOnError>
) =>
  (options?.client ?? client).get<HealthListResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/health',
    ...options,
  })

/**
 * Get Performance Metrics
 *
 * Get performance metrics and statistics.
 * Useful for monitoring application performance and identifying bottlenecks.
 */
export const metricsList = <ThrowOnError extends boolean = false>(
  options?: Options<MetricsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<MetricsListResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/metrics',
    ...options,
  })

/**
 * Get Endpoint Metrics
 *
 * Get detailed metrics for all endpoints.
 * Shows response times, error rates, and memory usage per endpoint.
 */
export const metricsEndpointsList = <ThrowOnError extends boolean = false>(
  options?: Options<MetricsEndpointsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    MetricsEndpointsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/metrics/endpoints',
    ...options,
  })

/**
 * Get Recent Requests
 *
 * Get recent request metrics for debugging.
 * Shows last N requests with timing and memory information.
 */
export const metricsRecentList = <ThrowOnError extends boolean = false>(
  options?: Options<MetricsRecentListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    MetricsRecentListResponses,
    MetricsRecentListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/metrics/recent',
    ...options,
  })

/**
 * Sign In Email
 *
 * Better Auth compatible email sign in.
 */
export const authSigninEmail = <ThrowOnError extends boolean = false>(
  options: Options<AuthSigninEmailData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthSigninEmailResponses,
    AuthSigninEmailErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/sign-in/email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Sign Up Email
 *
 * Better Auth compatible email sign up.
 */
export const authSignupEmail = <ThrowOnError extends boolean = false>(
  options: Options<AuthSignupEmailData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthSignupEmailResponses,
    AuthSignupEmailErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/sign-up/email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Sign Out
 *
 * Better Auth compatible sign out.
 */
export const authSignout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthSignoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<AuthSignoutResponses, unknown, ThrowOnError>(
    {
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/auth/sign-out',
      ...options,
    }
  )

/**
 * Get Session
 *
 * Get current session information.
 */
export const authSessionList = <ThrowOnError extends boolean = false>(
  options?: Options<AuthSessionListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthSessionListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/session',
    ...options,
  })

/**
 * Get Session Alias
 *
 * Alias for /auth/session.
 */
export const authGetsessionList = <ThrowOnError extends boolean = false>(
  options?: Options<AuthGetsessionListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthGetsessionListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/get-session',
    ...options,
  })

/**
 * Forgot Password
 *
 * Send password reset email to user.
 */
export const authForgotpassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthForgotpasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthForgotpasswordResponses,
    AuthForgotpasswordErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/forgot-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Reset Password
 *
 * Reset user password with token.
 */
export const authResetpassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthResetpasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthResetpasswordResponses,
    AuthResetpasswordErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/reset-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Oauth Authorize
 *
 * Get OAuth authorization URL for the specified provider.
 */
export const authOauthAuthorizeGetById = <ThrowOnError extends boolean = false>(
  options: Options<AuthOauthAuthorizeGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AuthOauthAuthorizeGetByIdResponses,
    AuthOauthAuthorizeGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/oauth/{provider}/authorize',
    ...options,
  })

/**
 * Oauth Callback
 *
 * Handle OAuth callback and create/login user.
 */
export const authOauthCallback = <ThrowOnError extends boolean = false>(
  options: Options<AuthOauthCallbackData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AuthOauthCallbackResponses,
    AuthOauthCallbackErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/oauth/{provider}/callback',
    ...options,
  })

/**
 * Link Oauth Account
 *
 * Link OAuth account to existing user account.
 */
export const authOauthLinkCreateById = <ThrowOnError extends boolean = false>(
  options: Options<AuthOauthLinkCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthOauthLinkCreateByIdResponses,
    AuthOauthLinkCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/oauth/{provider}/link',
    ...options,
  })

/**
 * Oauth Link Callback
 *
 * Handle OAuth link callback.
 */
export const authOauthLinkcallback = <ThrowOnError extends boolean = false>(
  options: Options<AuthOauthLinkcallbackData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AuthOauthLinkcallbackResponses,
    AuthOauthLinkcallbackErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/oauth/{provider}/link-callback',
    ...options,
  })

/**
 * Unlink Oauth Account
 *
 * Unlink OAuth account from user.
 */
export const authOauthUnlinkCreateById = <ThrowOnError extends boolean = false>(
  options: Options<AuthOauthUnlinkCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthOauthUnlinkCreateByIdResponses,
    AuthOauthUnlinkCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/oauth/{provider}/unlink',
    ...options,
  })

/**
 * Get Oauth Providers
 *
 * Get list of available OAuth providers.
 */
export const authOauthProvidersList = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOauthProvidersListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthOauthProvidersListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/oauth/providers',
    ...options,
  })

/**
 * List Organizations
 *
 * List user's organizations.
 */
export const authOrganizationList = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOrganizationListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthOrganizationListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization',
    ...options,
  })

/**
 * Create Organization
 *
 * Create organization.
 */
export const authOrganizationCreate = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOrganizationCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization',
    ...options,
  })

/**
 * List Organizations Compat
 *
 * Better Auth plugin expects /auth/organization/list.
 */
export const authOrganizationListList = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOrganizationListListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthOrganizationListListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/list',
    ...options,
  })

/**
 * Create Organization Alias
 *
 * Alias for /auth/organization.
 */
export const authOrganizationCreateCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationCreateCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationCreateCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/create',
    ...options,
  })

/**
 * Set Active Organization
 *
 * Set the active organization.
 */
export const authOrganizationSetactiveCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationSetactiveCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationSetactiveCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/set-active',
    ...options,
  })

/**
 * Delete Organization
 *
 * Delete organization.
 */
export const authOrganizationDeleteById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthOrganizationDeleteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    AuthOrganizationDeleteByIdResponses,
    AuthOrganizationDeleteByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/{org_id}',
    ...options,
  })

/**
 * Get Organization
 *
 * Get a specific organization.
 */
export const authOrganizationGetById = <ThrowOnError extends boolean = false>(
  options: Options<AuthOrganizationGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AuthOrganizationGetByIdResponses,
    AuthOrganizationGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/{org_id}',
    ...options,
  })

/**
 * Update Organization
 *
 * Update organization.
 */
export const authOrganizationUpdateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthOrganizationUpdateByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    AuthOrganizationUpdateByIdResponses,
    AuthOrganizationUpdateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/{org_id}',
    ...options,
  })

/**
 * List Members Endpoint
 *
 * List organization members - stub for compatibility.
 */
export const authOrganizationListmembersList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationListmembersListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthOrganizationListmembersListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/list-members',
    ...options,
  })

/**
 * Remove Member Endpoint
 *
 * Remove organization member - stub for compatibility.
 */
export const authOrganizationRemovememberCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationRemovememberCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationRemovememberCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/remove-member',
    ...options,
  })

/**
 * Update Member Role Endpoint
 *
 * Update member role - stub for compatibility.
 */
export const authOrganizationUpdatememberroleCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationUpdatememberroleCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationUpdatememberroleCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/update-member-role',
    ...options,
  })

/**
 * List Invitations Endpoint
 *
 * List invitations - stub for compatibility.
 */
export const authOrganizationListinvitationsList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationListinvitationsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthOrganizationListinvitationsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/list-invitations',
    ...options,
  })

/**
 * List User Invitations Endpoint
 *
 * List user invitations - stub for compatibility.
 */
export const authOrganizationListuserinvitationsList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationListuserinvitationsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthOrganizationListuserinvitationsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/list-user-invitations',
    ...options,
  })

/**
 * Invite Member Endpoint
 *
 * Invite member - stub for compatibility.
 */
export const authOrganizationInvitememberCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationInvitememberCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationInvitememberCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/invite-member',
    ...options,
  })

/**
 * Accept Invitation Endpoint
 *
 * Accept invitation - stub for compatibility.
 */
export const authOrganizationAcceptinvitationCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationAcceptinvitationCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationAcceptinvitationCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/accept-invitation',
    ...options,
  })

/**
 * Reject Invitation Endpoint
 *
 * Reject invitation - stub for compatibility.
 */
export const authOrganizationRejectinvitationCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationRejectinvitationCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationRejectinvitationCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/reject-invitation',
    ...options,
  })

/**
 * Cancel Invitation Endpoint
 *
 * Cancel invitation - stub for compatibility.
 */
export const authOrganizationCancelinvitationCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOrganizationCancelinvitationCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOrganizationCancelinvitationCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/organization/cancel-invitation',
    ...options,
  })

/**
 * Get Onboarding Status
 *
 * Get the current onboarding status for the user.
 */
export const authOnboardingStatusList = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOnboardingStatusListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthOnboardingStatusListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/onboarding/status',
    ...options,
  })

/**
 * Update Onboarding Profile
 *
 * Update user profile during onboarding.
 */
export const authOnboardingProfileUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthOnboardingProfileUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    AuthOnboardingProfileUpdateResponses,
    AuthOnboardingProfileUpdateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/onboarding/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Create Onboarding Organization
 *
 * Create user's first organization during onboarding.
 */
export const authOnboardingOrganizationCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOnboardingOrganizationCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOnboardingOrganizationCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/onboarding/organization',
    ...options,
  })

/**
 * Update Onboarding Step
 *
 * Update the current onboarding step.
 */
export const authOnboardingStepUpdate = <ThrowOnError extends boolean = false>(
  options: Options<AuthOnboardingStepUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    AuthOnboardingStepUpdateResponses,
    AuthOnboardingStepUpdateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/onboarding/step',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Complete Onboarding
 *
 * Mark onboarding as completed and send welcome email.
 */
export const authOnboardingCompleteCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthOnboardingCompleteCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthOnboardingCompleteCreateResponses,
    AuthOnboardingCompleteCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/onboarding/complete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Save All Onboarding Data
 *
 * Save all onboarding data at once (profile + organization).
 */
export const authOnboardingSaveallCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthOnboardingSaveallCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthOnboardingSaveallCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/onboarding/save-all',
    ...options,
  })

/**
 * Send Otp
 *
 * Send OTP code to email for registration or login.
 */
export const authOtpSendCreate = <ThrowOnError extends boolean = false>(
  options: Options<AuthOtpSendCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthOtpSendCreateResponses,
    AuthOtpSendCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/otp/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Verify Otp
 *
 * Verify OTP code and complete registration or login.
 */
export const authOtpVerify = <ThrowOnError extends boolean = false>(
  options: Options<AuthOtpVerifyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthOtpVerifyResponses,
    AuthOtpVerifyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/otp/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Auth:Jwt.Login
 */
export const authJwtLoginCreate = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthJwtLoginCreateResponses,
    AuthJwtLoginCreateErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/jwt/login',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  })

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogoutCreate = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthJwtLogoutCreateResponses,
    AuthJwtLogoutCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/jwt/logout',
    ...options,
  })

/**
 * Register:Register
 */
export const authRegisterCreate = <ThrowOnError extends boolean = false>(
  options: Options<AuthRegisterCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthRegisterCreateResponses,
    AuthRegisterCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Verify:Request-Token
 */
export const authRequestverifytoken = <ThrowOnError extends boolean = false>(
  options: Options<AuthRequestverifytokenData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthRequestverifytokenResponses,
    AuthRequestverifytokenErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/request-verify-token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Verify:Verify
 */
export const authVerify = <ThrowOnError extends boolean = false>(
  options: Options<AuthVerifyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthVerifyResponses,
    AuthVerifyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Verify Email
 *
 * Verify user email with token.
 */
export const authVerifyemail = <ThrowOnError extends boolean = false>(
  options: Options<AuthVerifyemailData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthVerifyemailResponses,
    AuthVerifyemailErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/verify-email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Resend Verification
 *
 * Resend email verification.
 */
export const authResendverification = <ThrowOnError extends boolean = false>(
  options: Options<AuthResendverificationData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthResendverificationResponses,
    AuthResendverificationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/resend-verification',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Current User
 *
 * Get current user profile
 */
export const meList = <ThrowOnError extends boolean = false>(
  options?: Options<MeListData, ThrowOnError>
) =>
  (options?.client ?? client).get<MeListResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/me',
    ...options,
  })

/**
 * Update Current User
 *
 * Update current user profile
 */
export const meUpdate = <ThrowOnError extends boolean = false>(
  options: Options<MeUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    MeUpdateResponses,
    MeUpdateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/me',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * List Users
 *
 * List users with pagination and search
 */
export const usersList = <ThrowOnError extends boolean = false>(
  options?: Options<UsersListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    UsersListResponses,
    UsersListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/users',
    ...options,
  })

/**
 * Get User Profile
 *
 * Get user profile by email
 */
export const usersGetById = <ThrowOnError extends boolean = false>(
  options: Options<UsersGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UsersGetByIdResponses,
    UsersGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/users/{email}',
    ...options,
  })

/**
 * Get Available Languages
 *
 * Get list of supported languages
 */
export const i18nLanguagesList = <ThrowOnError extends boolean = false>(
  options?: Options<I18nLanguagesListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    I18nLanguagesListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/i18n/languages',
    ...options,
  })

/**
 * Test Translation
 *
 * Test translation endpoint - returns translated message based on Accept-Language header
 */
export const i18nTestList = <ThrowOnError extends boolean = false>(
  options?: Options<I18nTestListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    I18nTestListResponses,
    I18nTestListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/i18n/test',
    ...options,
  })

/**
 * Test Pluralization
 *
 * Test pluralization endpoint - demonstrates plural forms in different languages
 */
export const i18nPluralizationList = <ThrowOnError extends boolean = false>(
  options?: Options<I18nPluralizationListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    I18nPluralizationListResponses,
    I18nPluralizationListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/i18n/pluralization',
    ...options,
  })

/**
 * Get Localized Datetime
 *
 * Returns current datetime formatted according to the user's locale
 */
export const i18nDatetimeList = <ThrowOnError extends boolean = false>(
  options?: Options<I18nDatetimeListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    I18nDatetimeListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/i18n/datetime',
    ...options,
  })

/**
 * List All Users
 *
 * List all users with pagination and search (Admin only)
 */
export const adminUsersList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminUsersListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AdminUsersListResponses,
    AdminUsersListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/users',
    ...options,
  })

/**
 * Delete User
 *
 * Delete user (Admin only)
 */
export const adminUsersDeleteById = <ThrowOnError extends boolean = false>(
  options: Options<AdminUsersDeleteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    AdminUsersDeleteByIdResponses,
    AdminUsersDeleteByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/users/{user_id}',
    ...options,
  })

/**
 * Get User By Id
 *
 * Get user by ID (Admin only)
 */
export const adminUsersGetById = <ThrowOnError extends boolean = false>(
  options: Options<AdminUsersGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AdminUsersGetByIdResponses,
    AdminUsersGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/users/{user_id}',
    ...options,
  })

/**
 * Update User
 *
 * Update user (Admin only)
 */
export const adminUsersUpdateById = <ThrowOnError extends boolean = false>(
  options: Options<AdminUsersUpdateByIdData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    AdminUsersUpdateByIdResponses,
    AdminUsersUpdateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Admin Stats
 *
 * Get admin statistics (Admin only)
 */
export const adminStatsList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminStatsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AdminStatsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/stats',
    ...options,
  })

/**
 * Invite User
 *
 * Invite a new user (Admin only)
 * Creates user account with temporary password
 */
export const adminUsersInviteCreate = <ThrowOnError extends boolean = false>(
  options: Options<AdminUsersInviteCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AdminUsersInviteCreateResponses,
    AdminUsersInviteCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/users/invite',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Analytics Overview
 *
 * Get analytics overview for reports dashboard (Admin only)
 */
export const adminAnalyticsOverviewList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminAnalyticsOverviewListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AdminAnalyticsOverviewListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/analytics/overview',
    ...options,
  })

/**
 * Get Users Growth
 *
 * Get user growth data for charts (Admin only)
 */
export const adminAnalyticsUsersgrowthList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminAnalyticsUsersgrowthListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AdminAnalyticsUsersgrowthListResponses,
    AdminAnalyticsUsersgrowthListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/analytics/users-growth',
    ...options,
  })

/**
 * Get Revenue Chart
 *
 * Get revenue data for charts (Admin only)
 */
export const adminAnalyticsRevenuechartList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminAnalyticsRevenuechartListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AdminAnalyticsRevenuechartListResponses,
    AdminAnalyticsRevenuechartListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/analytics/revenue-chart',
    ...options,
  })

/**
 * List Activity Logs
 *
 * List activity logs with pagination and filters (Admin only)
 */
export const adminActivitylogsList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminActivitylogsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AdminActivitylogsListResponses,
    AdminActivitylogsListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/activity-logs',
    ...options,
  })

/**
 * Get Current User Profile
 *
 * Get current user's profile.
 */
export const usersMeList = <ThrowOnError extends boolean = false>(
  options?: Options<UsersMeListData, ThrowOnError>
) =>
  (options?.client ?? client).get<UsersMeListResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/users/me',
    ...options,
  })

/**
 * Update Current User Profile
 *
 * Update current user's profile.
 */
export const usersMeUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UsersMeUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UsersMeUpdateResponses,
    UsersMeUpdateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/users/me',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Upload User Profile Image
 *
 * Upload user profile image to R2 storage.
 */
export const usersMeUploadimageCreate = <ThrowOnError extends boolean = false>(
  options: Options<UsersMeUploadimageCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UsersMeUploadimageCreateResponses,
    UsersMeUploadimageCreateErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/users/me/upload-image',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })

/**
 * Delete User Profile Image
 *
 * Delete user's profile image.
 */
export const usersMeImageDelete = <ThrowOnError extends boolean = false>(
  options?: Options<UsersMeImageDeleteData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    UsersMeImageDeleteResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/users/me/image',
    ...options,
  })

/**
 * Resend Verification Email
 *
 * Resend email verification.
 */
export const invitationsVerifyemailResend = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<InvitationsVerifyemailResendData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    InvitationsVerifyemailResendResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/invitations/verify-email/resend',
    ...options,
  })

/**
 * Verify Email
 *
 * Verify email with token.
 */
export const invitationsVerifyemail = <ThrowOnError extends boolean = false>(
  options: Options<InvitationsVerifyemailData, ThrowOnError>
) =>
  (options.client ?? client).post<
    InvitationsVerifyemailResponses,
    InvitationsVerifyemailErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/invitations/verify-email/{token}',
    ...options,
  })

/**
 * List Invitations
 *
 * List all pending invitations for an organization.
 */
export const invitationsOrganizationsInvitationsGetById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvitationsOrganizationsInvitationsGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    InvitationsOrganizationsInvitationsGetByIdResponses,
    InvitationsOrganizationsInvitationsGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/invitations/organizations/{organization_id}/invitations',
    ...options,
  })

/**
 * Invite Team Member
 *
 * Invite a new team member to organization.
 */
export const invitationsOrganizationsInvitationsCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    InvitationsOrganizationsInvitationsCreateByIdData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    InvitationsOrganizationsInvitationsCreateByIdResponses,
    InvitationsOrganizationsInvitationsCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/invitations/organizations/{organization_id}/invitations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Accept Invitation
 *
 * Accept team invitation.
 */
export const invitationsInvitationsAcceptCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvitationsInvitationsAcceptCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    InvitationsInvitationsAcceptCreateByIdResponses,
    InvitationsInvitationsAcceptCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/invitations/invitations/{token}/accept',
    ...options,
  })

/**
 * Decline Invitation
 *
 * Decline team invitation.
 */
export const invitationsInvitationsDeclineCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvitationsInvitationsDeclineCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    InvitationsInvitationsDeclineCreateByIdResponses,
    InvitationsInvitationsDeclineCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/invitations/invitations/{token}/decline',
    ...options,
  })

/**
 * Cancel Invitation
 *
 * Cancel a pending invitation.
 */
export const invitationsOrganizationsInvitationsDeleteById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    InvitationsOrganizationsInvitationsDeleteByIdData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    InvitationsOrganizationsInvitationsDeleteByIdResponses,
    InvitationsOrganizationsInvitationsDeleteByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/invitations/organizations/{organization_id}/invitations/{invitation_id}',
    ...options,
  })

/**
 * Get Organizations
 */
export const organizationsList = <ThrowOnError extends boolean = false>(
  options?: Options<OrganizationsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    OrganizationsListResponses,
    OrganizationsListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/organizations/',
    ...options,
  })

/**
 * Create New Organization
 */
export const organizationsCreate = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationsCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    OrganizationsCreateResponses,
    OrganizationsCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/organizations/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Invite Member
 */
export const organizationsInviteCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrganizationsInviteCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    OrganizationsInviteCreateByIdResponses,
    OrganizationsInviteCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/organizations/{organization_id}/invite',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Export Organizations Json
 *
 * Export all user organizations as streaming JSON.
 * Reduces memory usage by streaming results instead of loading all data at once.
 */
export const organizationsExportJsonList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OrganizationsExportJsonListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    OrganizationsExportJsonListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/organizations/export/json',
    ...options,
  })

/**
 * Export Organizations Csv
 *
 * Export all user organizations as streaming CSV.
 * Memory-efficient export for large datasets.
 */
export const organizationsExportCsvList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OrganizationsExportCsvListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    OrganizationsExportCsvListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/organizations/export/csv',
    ...options,
  })

/**
 * Upload Organization Logo
 *
 * Upload organization logo to R2 storage.
 */
export const organizationsUploadlogoCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrganizationsUploadlogoCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    OrganizationsUploadlogoCreateByIdResponses,
    OrganizationsUploadlogoCreateByIdErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/organizations/{organization_id}/upload-logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })

/**
 * Delete Organization Logo
 *
 * Delete organization logo.
 */
export const organizationsLogoDeleteById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrganizationsLogoDeleteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    OrganizationsLogoDeleteByIdResponses,
    OrganizationsLogoDeleteByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/organizations/{organization_id}/logo',
    ...options,
  })

/**
 * List Projects
 */
export const projectsList = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ProjectsListResponses,
    ProjectsListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/',
    ...options,
  })

/**
 * Create New Project
 */
export const projectsCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ProjectsCreateResponses,
    ProjectsCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete Project By Id
 */
export const projectsDeleteById = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsDeleteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ProjectsDeleteByIdResponses,
    ProjectsDeleteByIdErrors,
    ThrowOnError
  >({ url: '/api/v1/projects/{project_id}', ...options })

/**
 * Get Project By Id
 */
export const projectsGetById = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ProjectsGetByIdResponses,
    ProjectsGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/{project_id}',
    ...options,
  })

/**
 * Update Project By Id
 */
export const projectsUpdateById = <ThrowOnError extends boolean = false>(
  options: Options<ProjectsUpdateByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ProjectsUpdateByIdResponses,
    ProjectsUpdateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/{project_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Export Projects Json
 *
 * Export all user projects as streaming JSON.
 * Memory-efficient export for large project datasets.
 */
export const projectsExportJsonList = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectsExportJsonListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ProjectsExportJsonListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/export/json',
    ...options,
  })

/**
 * Export Projects Csv
 *
 * Export all user projects as streaming CSV.
 * Efficient export for spreadsheet analysis.
 */
export const projectsExportCsvList = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectsExportCsvListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ProjectsExportCsvListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/export/csv',
    ...options,
  })

/**
 * List Plans
 */
export const paymentsPlansList = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsPlansListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    PaymentsPlansListResponses,
    PaymentsPlansListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/payments/plans',
    ...options,
  })

/**
 * Create Subscription
 */
export const paymentsSubscribeCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsSubscribeCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PaymentsSubscribeCreateByIdResponses,
    PaymentsSubscribeCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/payments/{organization_id}/subscribe',
    ...options,
  })

/**
 * Stripe Webhook
 */
export const paymentsStripewebhookCreate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PaymentsStripewebhookCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PaymentsStripewebhookCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/payments/stripe-webhook',
    ...options,
  })

/**
 * List Subscription Plans
 *
 * Get all available subscription plans.
 */
export const subscriptionsPlansList = <ThrowOnError extends boolean = false>(
  options?: Options<SubscriptionsPlansListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    SubscriptionsPlansListResponses,
    SubscriptionsPlansListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/subscriptions/plans',
    ...options,
  })

/**
 * Create Subscription Checkout
 *
 * Create a Stripe checkout session for subscribing to a plan.
 */
export const subscriptionsOrganizationsCheckoutCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubscriptionsOrganizationsCheckoutCreateByIdData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    SubscriptionsOrganizationsCheckoutCreateByIdResponses,
    SubscriptionsOrganizationsCheckoutCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/subscriptions/organizations/{organization_id}/checkout',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Organization Subscription Details
 *
 * Get organization's current subscription details.
 */
export const subscriptionsOrganizationsSubscriptionGetById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubscriptionsOrganizationsSubscriptionGetByIdData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    SubscriptionsOrganizationsSubscriptionGetByIdResponses,
    SubscriptionsOrganizationsSubscriptionGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/subscriptions/organizations/{organization_id}/subscription',
    ...options,
  })

/**
 * Get Customer Portal
 *
 * Get Stripe customer portal URL for managing billing.
 */
export const subscriptionsOrganizationsPortalCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SubscriptionsOrganizationsPortalCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SubscriptionsOrganizationsPortalCreateByIdResponses,
    SubscriptionsOrganizationsPortalCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/subscriptions/organizations/{organization_id}/portal',
    ...options,
  })

/**
 * Cancel Organization Subscription
 *
 * Cancel organization's subscription (at end of billing period).
 */
export const subscriptionsOrganizationsCancelCreateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SubscriptionsOrganizationsCancelCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SubscriptionsOrganizationsCancelCreateByIdResponses,
    SubscriptionsOrganizationsCancelCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/subscriptions/organizations/{organization_id}/cancel',
    ...options,
  })

/**
 * Get Organization Usage
 *
 * Get organization's subscription usage metrics.
 */
export const subscriptionsOrganizationsUsageGetById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SubscriptionsOrganizationsUsageGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    SubscriptionsOrganizationsUsageGetByIdResponses,
    SubscriptionsOrganizationsUsageGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/subscriptions/organizations/{organization_id}/usage',
    ...options,
  })

/**
 * Get Organization Billing History
 *
 * Get organization's billing history.
 */
export const subscriptionsOrganizationsBillinghistoryGetById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubscriptionsOrganizationsBillinghistoryGetByIdData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    SubscriptionsOrganizationsBillinghistoryGetByIdResponses,
    SubscriptionsOrganizationsBillinghistoryGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/subscriptions/organizations/{organization_id}/billing-history',
    ...options,
  })

/**
 * Stripe Webhook
 *
 * Handle Stripe webhook events for subscriptions.
 */
export const webhooksStripeCreate = <ThrowOnError extends boolean = false>(
  options?: Options<WebhooksStripeCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    WebhooksStripeCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/webhooks/stripe',
    ...options,
  })

/**
 * Upload File
 */
export const uploadsCreate = <ThrowOnError extends boolean = false>(
  options: Options<UploadsCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadsCreateResponses,
    UploadsCreateErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/uploads/',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })

/**
 * Delete File
 */
export const uploadsDeleteById = <ThrowOnError extends boolean = false>(
  options: Options<UploadsDeleteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UploadsDeleteByIdResponses,
    UploadsDeleteByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/uploads/{key}',
    ...options,
  })

/**
 * Get Presigned Url
 */
export const uploadsUrlGetById = <ThrowOnError extends boolean = false>(
  options: Options<UploadsUrlGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UploadsUrlGetByIdResponses,
    UploadsUrlGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/uploads/{key}/url',
    ...options,
  })

/**
 * Get Ai Usage Dashboard
 *
 * Get AI usage dashboard data.
 */
export const aiUsageDashboardList = <ThrowOnError extends boolean = false>(
  options?: Options<AiUsageDashboardListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiUsageDashboardListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-usage/dashboard',
    ...options,
  })

/**
 * Get Usage Limits
 *
 * Get current usage limits and status.
 */
export const aiUsageLimitsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiUsageLimitsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiUsageLimitsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-usage/limits',
    ...options,
  })

/**
 * Get Recent Ai Activity
 *
 * Get recent AI activity for the user's organization.
 */
export const aiUsageRecentactivityList = <ThrowOnError extends boolean = false>(
  options?: Options<AiUsageRecentactivityListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiUsageRecentactivityListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-usage/recent-activity',
    ...options,
  })

/**
 * Get Usage Summary
 *
 * Get AI usage summary for the last N days.
 */
export const aiBillingUsagesummaryList = <ThrowOnError extends boolean = false>(
  options?: Options<AiBillingUsagesummaryListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiBillingUsagesummaryListResponses,
    AiBillingUsagesummaryListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-billing/usage-summary',
    ...options,
  })

/**
 * Get Billing Period
 *
 * Get AI usage bill for a specific billing period.
 */
export const aiBillingBillingperiodList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiBillingBillingperiodListData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiBillingBillingperiodListResponses,
    AiBillingBillingperiodListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-billing/billing-period',
    ...options,
  })

/**
 * Get Ai Stats
 *
 * Get comprehensive AI statistics for the organization.
 */
export const aiBillingStatsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiBillingStatsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiBillingStatsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-billing/stats',
    ...options,
  })

/**
 * Check Usage Limits
 *
 * Check if organization can use AI feature within limits.
 */
export const aiBillingChecklimitsList = <ThrowOnError extends boolean = false>(
  options: Options<AiBillingChecklimitsListData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiBillingChecklimitsListResponses,
    AiBillingChecklimitsListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-billing/check-limits',
    ...options,
  })

/**
 * Get Monthly Report
 *
 * Get detailed monthly AI usage report.
 */
export const aiBillingMonthlyreportList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiBillingMonthlyreportListData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiBillingMonthlyreportListResponses,
    AiBillingMonthlyreportListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-billing/monthly-report',
    ...options,
  })

/**
 * Get Dashboard Overview
 *
 * Get comprehensive AI dashboard overview.
 */
export const aiDashboardOverviewList = <ThrowOnError extends boolean = false>(
  options?: Options<AiDashboardOverviewListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiDashboardOverviewListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-dashboard/overview',
    ...options,
  })

/**
 * Get Usage Trends
 *
 * Get AI usage trends over time.
 */
export const aiDashboardTrendsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiDashboardTrendsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiDashboardTrendsListResponses,
    AiDashboardTrendsListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-dashboard/trends',
    ...options,
  })

/**
 * Get Feature Insights
 *
 * Get AI feature usage insights and recommendations.
 */
export const aiDashboardInsightsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiDashboardInsightsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiDashboardInsightsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-dashboard/insights',
    ...options,
  })

/**
 * Get Ai Metrics
 *
 * Get key AI metrics for quick overview.
 */
export const aiDashboardMetricsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiDashboardMetricsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiDashboardMetricsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-dashboard/metrics',
    ...options,
  })

/**
 * Upload Document
 *
 * Upload a document for AI processing.
 */
export const aiDocumentsUploadCreate = <ThrowOnError extends boolean = false>(
  options: Options<AiDocumentsUploadCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AiDocumentsUploadCreateResponses,
    AiDocumentsUploadCreateErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/ai-documents/upload',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })

/**
 * Get Documents
 *
 * Get documents for the user's organization.
 */
export const aiDocumentsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiDocumentsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiDocumentsListResponses,
    AiDocumentsListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-documents/',
    ...options,
  })

/**
 * Delete Document
 *
 * Delete a document.
 */
export const aiDocumentsDeleteById = <ThrowOnError extends boolean = false>(
  options: Options<AiDocumentsDeleteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    AiDocumentsDeleteByIdResponses,
    AiDocumentsDeleteByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-documents/{document_id}',
    ...options,
  })

/**
 * Get Document
 *
 * Get a specific document.
 */
export const aiDocumentsGetById = <ThrowOnError extends boolean = false>(
  options: Options<AiDocumentsGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiDocumentsGetByIdResponses,
    AiDocumentsGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-documents/{document_id}',
    ...options,
  })

/**
 * Get Document Status
 *
 * Get document processing status.
 */
export const aiDocumentsStatusGetById = <ThrowOnError extends boolean = false>(
  options: Options<AiDocumentsStatusGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiDocumentsStatusGetByIdResponses,
    AiDocumentsStatusGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-documents/{document_id}/status',
    ...options,
  })

/**
 * Chat With Document
 *
 * Chat with a document using AI.
 */
export const aiDocumentsChatCreateById = <ThrowOnError extends boolean = false>(
  options: Options<AiDocumentsChatCreateByIdData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AiDocumentsChatCreateByIdResponses,
    AiDocumentsChatCreateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-documents/{document_id}/chat',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Document Chats
 *
 * Get chat history for a document.
 */
export const aiDocumentsChatsGetById = <ThrowOnError extends boolean = false>(
  options: Options<AiDocumentsChatsGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiDocumentsChatsGetByIdResponses,
    AiDocumentsChatsGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-documents/{document_id}/chats',
    ...options,
  })

/**
 * Get Ai Content Info
 *
 * Get AI Content service information.
 */
export const aiContentList = <ThrowOnError extends boolean = false>(
  options?: Options<AiContentListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiContentListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/',
    ...options,
  })

/**
 * Get Templates
 *
 * Get content templates for the user's organization.
 */
export const aiContentTemplatesList = <ThrowOnError extends boolean = false>(
  options?: Options<AiContentTemplatesListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiContentTemplatesListResponses,
    AiContentTemplatesListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/templates',
    ...options,
  })

/**
 * Create Template
 *
 * Create a new content template.
 */
export const aiContentTemplatesCreate = <ThrowOnError extends boolean = false>(
  options: Options<AiContentTemplatesCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AiContentTemplatesCreateResponses,
    AiContentTemplatesCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete Template
 *
 * Delete a template.
 */
export const aiContentTemplatesDeleteById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiContentTemplatesDeleteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    AiContentTemplatesDeleteByIdResponses,
    AiContentTemplatesDeleteByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/templates/{template_id}',
    ...options,
  })

/**
 * Get Template
 *
 * Get a specific template.
 */
export const aiContentTemplatesGetById = <ThrowOnError extends boolean = false>(
  options: Options<AiContentTemplatesGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiContentTemplatesGetByIdResponses,
    AiContentTemplatesGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/templates/{template_id}',
    ...options,
  })

/**
 * Update Template
 *
 * Update a template.
 */
export const aiContentTemplatesUpdateById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiContentTemplatesUpdateByIdData, ThrowOnError>
) =>
  (options.client ?? client).put<
    AiContentTemplatesUpdateByIdResponses,
    AiContentTemplatesUpdateByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/templates/{template_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Generate Content
 *
 * Generate content using AI.
 */
export const aiContentGenerateCreate = <ThrowOnError extends boolean = false>(
  options: Options<AiContentGenerateCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AiContentGenerateCreateResponses,
    AiContentGenerateCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/generate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Generations
 *
 * Get content generation history for the current user.
 */
export const aiContentGenerationsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiContentGenerationsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiContentGenerationsListResponses,
    AiContentGenerationsListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/generations',
    ...options,
  })

/**
 * Get Generation
 *
 * Get a specific generation.
 */
export const aiContentGenerationsGetById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiContentGenerationsGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiContentGenerationsGetByIdResponses,
    AiContentGenerationsGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/generations/{generation_id}',
    ...options,
  })

/**
 * Get Content Stats
 *
 * Get content generation statistics for the user's organization.
 */
export const aiContentStatsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiContentStatsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiContentStatsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-content/stats',
    ...options,
  })

/**
 * Process Analytics Query
 *
 * Process a natural language analytics query.
 */
export const aiAnalyticsQueryCreate = <ThrowOnError extends boolean = false>(
  options: Options<AiAnalyticsQueryCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AiAnalyticsQueryCreateResponses,
    AiAnalyticsQueryCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-analytics/query',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Queries
 *
 * Get analytics queries for the user's organization.
 */
export const aiAnalyticsQueriesList = <ThrowOnError extends boolean = false>(
  options?: Options<AiAnalyticsQueriesListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiAnalyticsQueriesListResponses,
    AiAnalyticsQueriesListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-analytics/queries',
    ...options,
  })

/**
 * Get Query
 *
 * Get a specific analytics query.
 */
export const aiAnalyticsQueriesGetById = <ThrowOnError extends boolean = false>(
  options: Options<AiAnalyticsQueriesGetByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AiAnalyticsQueriesGetByIdResponses,
    AiAnalyticsQueriesGetByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-analytics/queries/{query_id}',
    ...options,
  })

/**
 * Get Analytics Stats
 *
 * Get analytics usage statistics for the user's organization.
 */
export const aiAnalyticsStatsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiAnalyticsStatsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiAnalyticsStatsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-analytics/stats',
    ...options,
  })

/**
 * Get Quick Insights
 *
 * Get quick insights about the organization's data.
 */
export const aiAnalyticsInsightsList = <ThrowOnError extends boolean = false>(
  options?: Options<AiAnalyticsInsightsListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AiAnalyticsInsightsListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/ai-analytics/insights',
    ...options,
  })
